name: Deploy to Raspberry Pi

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: [self-hosted, kmellon_raspi]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Deploy with Docker Compose
        run: |
          docker compose -f docker-compose.deploy.yaml pull --ignore-pull-failures
          docker compose -f docker-compose.deploy.yaml up -d --build
          docker compose -f docker-compose.deploy.yaml ps

      - name: Clean up .env
        if: always()
        run: rm -f ./.env
